# Generated by Django 4.0.6 on 2022-07-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Title')),
                ('created_on', models.DateTimeField(auto_now=True, verbose_name='Scrupping Time')),
            ],
            options={
                'db_table': 'AllNews',
            },
        ),
    ]
