# Generated by Django 4.0.6 on 2022-07-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allnews',
            name='link',
            field=models.CharField(default='/', max_length=200, verbose_name='Link'),
        ),
    ]
