# Generated by Django 4.0.6 on 2022-07-25 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_allnews_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allnews',
            options={'ordering': ['-created_on'], 'verbose_name': 'All News', 'verbose_name_plural': 'All News'},
        ),
        migrations.AlterModelTable(
            name='allnews',
            table=None,
        ),
    ]
